color: null
fieldLayouts:
  a2bae6e5-b24f-480c-8840-77318c35fe87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T10:44:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bfab3bd8-d6eb-4c0f-a8ea-461ece283cb7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-08T14:34:46+00:00'
            elementCondition: null
            fieldUid: 38c1e2e9-c1e3-4c80-acfe-f190d86317fa # Lead Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f75053de-6c04-4645-a9f5-f88d93ccbf0a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T10:45:45+00:00'
            elementCondition: null
            fieldUid: 766fa7b3-abd7-40fb-aa55-b6bda45069cd # Google Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 354464c7-9d21-4189-9f3a-1d1349ebce86
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T11:46:25+00:00'
            elementCondition: null
            fieldUid: 2bd2e1b6-0fec-42ee-9bbb-a384eaecd9c9 # Bild
            handle: null
            includeInCards: false
            instructions: null
            label: Aufmacherbild
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adf71057-53e3-4784-9ae3-db24387e946c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T11:06:12+00:00'
            elementCondition: null
            fieldUid: 91725092-8f89-4299-a39d-14eaaeef57ae # Rubrik
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e058395e-3601-40ef-88b6-c85b0e9dcfb1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-18T11:06:12+00:00'
            elementCondition: null
            fieldUid: 2897cc3f-95c9-4148-80b9-fd663d11f977 # Thema
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d4dc202-9a02-4984-8cc1-3a6840b5229c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-18T14:33:52+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3993fac1-ba1c-454c-9013-425272f0f6b1
            userCondition: null
          -
            dateAdded: '2024-12-18T11:08:52+00:00'
            elementCondition: null
            fieldUid: d78e16f8-76f5-495a-a21a-bbd7cc75dc97 # Artikel Blöcke
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2d32664-61c3-43b9-8325-d286c231ae69
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-08T13:10:34+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ee41adaf-27dd-4848-ae62-3ce46053b2b3
            userCondition: null
        name: Inhalt
        uid: d7eeb8cf-bc12-4c92-b8cc-3ef09c800bff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-08T13:10:34+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: "1. In Texteditor für Verortung der Fussnote ein X hochgestellt einsetzen\r\n2. Fussnoten entsprechend der Reihenfolge einfügen.\r\n3. Die nummerierung wird dann vom System automatisch vergeben"
            type: craft\fieldlayoutelements\Tip
            uid: c66d513b-cf50-464d-87e6-f46db72a09f1
            userCondition: null
          -
            dateAdded: '2025-01-08T13:10:34+00:00'
            elementCondition: null
            fieldUid: 38431ae0-6666-499d-a0a8-a2a332b0b6ce
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca59bed8-6bf9-43d3-8b7a-fb000c497bd9
            userCondition: null
            warning: null
            width: 100
        name: Quellen
        uid: 812ef1ba-2337-4f06-9c7a-b512aa0eaaeb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T10:52:25+00:00'
            elementCondition: null
            fieldUid: 8615cf7b-5ca8-4def-a0f2-1370cdee3c8e # SEO Article
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d14bd53-0ba2-4789-b3c7-03556beb5ce1
            userCondition: null
            warning: null
            width: 100
        name: Google
        uid: 132df382-76c4-4b56-ab8f-95fb71743dd4
        userCondition: null
handle: artikelSet
hasTitleField: true
icon: null
name: 'Artikel Set'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
