color: null
fieldLayouts:
  9eb71394-1e19-4afa-b424-60e2d602b7d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T08:01:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b84d7296-105e-4cd2-a351-d84b70fcfbfb # Article Img i18n
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e004b8db-a4fd-4096-abd1-8fa0f2b3a24a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0dd90caa-0a5d-48ef-8331-204f105d5d90
        userCondition: null
handle: articleImgI18n
hasTitleField: false
icon: image-polaroid
name: 'Image i18n'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
