color: null
fieldLayouts:
  55060bd9-75b4-4130-b5cb-0fb44c1e3983:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T11:22:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2bd2e1b6-0fec-42ee-9bbb-a384eaecd9c9 # Article Img
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a02c9b34-e74f-4b59-9476-d9477ac44116
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T07:28:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 826bddc1-fa89-4b66-b1ab-6924ab5aa9c3 # Plain Text i18n Multiline
            handle: null
            includeInCards: false
            instructions: null
            label: Bildlegende
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f941e2d-0d96-43b6-8e5b-26670955e460
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-04-29T07:32:47+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Bildquelle: Doppelklick aufs Bild'
            type: craft\fieldlayoutelements\Tip
            uid: 1aec61e3-44c2-4574-80f6-ca95dd325fc2
            userCondition: null
        name: Inhalt
        uid: dccca97d-5f11-4b2a-9bbc-07072ff38814
        userCondition: null
handle: articleImg
hasTitleField: false
icon: image
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
