color: null
fieldLayouts:
  ba018980-2dd6-45ab-b31e-2658e30cdf0e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-19T11:24:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9442ba70-0917-40f4-8ccc-5d84501c8848
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-19T11:25:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b84d7296-105e-4cd2-a351-d84b70fcfbfb # Article Img i18n
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44d8ed52-7643-4e15-a450-4c663a34845d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-19T11:25:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text i18n
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9da75b6d-b47a-469f-9699-a0fb6ddfead0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6601a8b5-ec05-4c04-b4f3-25a83bfdf20c
        userCondition: null
handle: cCTA
hasTitleField: true
icon: null
name: 'CTA Type'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
