color: null
fieldLayouts:
  63c70567-8281-4c5f-9dae-73e288e87634:
    cardView:
      - 'layoutElement:be8eced6-7257-4a31-a5ae-aac01139fd0d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T14:39:20+00:00'
            elementCondition: null
            fieldUid: 38c1e2e9-c1e3-4c80-acfe-f190d86317fa # Plain Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7cca186-6a29-492e-8db3-cfd33a11eb91
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-12-18T11:21:29+00:00'
            elementCondition: null
            fieldUid: b572ca4f-491d-4184-8bba-ebf12597ed59 # Plain Tex Line
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be8eced6-7257-4a31-a5ae-aac01139fd0d
            userCondition: null
            warning: null
            width: 25
        name: Inhalt
        uid: 80ae1dd6-4f37-4682-99fb-5950713e3a10
        userCondition: null
handle: cellQuote
hasTitleField: false
icon: quote-left
name: Zitat
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
