color: null
fieldLayouts:
  55060bd9-75b4-4130-b5cb-0fb44c1e3983:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T11:22:33+00:00'
            elementCondition: null
            fieldUid: 2bd2e1b6-0fec-42ee-9bbb-a384eaecd9c9 # Bild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a02c9b34-e74f-4b59-9476-d9477ac44116
            userCondition: null
            warning: null
            width: 25
        name: Inhalt
        uid: dccca97d-5f11-4b2a-9bbc-07072ff38814
        userCondition: null
handle: cellImgMonoLingual
hasTitleField: false
icon: image
name: 'Bild Monolingual'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
