color: null
fieldLayouts:
  c1c33481-6c7d-4b77-b4f9-b5e160ddfcd2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T11:38:19+00:00'
            elementCondition: null
            heading: 'Der klassische blaue Kasten aus dem Inforaum für Zusatzinfos'
            type: craft\fieldlayoutelements\Heading
            uid: 0efc282b-8345-43f2-b1ed-9153ff62cfa4
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T11:35:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 07ae4c59-b0ad-44d8-8bfd-a1cc493e6a39
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T11:38:19+00:00'
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a5e8d45-10ce-458d-b464-69f56653ca78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T11:38:19+00:00'
            elementCondition: null
            fieldUid: 212f7ab4-64f9-4b3c-92e4-fc78442435a9 # Url
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fb919e8-4a3f-4dff-a45b-36d0b55945b8
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 1fc15a0d-6f6a-4fc0-8e61-4c7506104737
        userCondition: null
handle: cellBox
hasTitleField: true
icon: cart-flatbed-boxes
name: Kasten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
