color: null
fieldLayouts:
  63c70567-8281-4c5f-9dae-73e288e87634:
    cardView:
      - 'layoutElement:7f46965c-055b-4025-93c0-2c3230abcad0'
      - 'layoutElement:be8eced6-7257-4a31-a5ae-aac01139fd0d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T11:21:29+00:00'
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f46965c-055b-4025-93c0-2c3230abcad0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T11:21:29+00:00'
            elementCondition: null
            fieldUid: b572ca4f-491d-4184-8bba-ebf12597ed59 # Zitat Quelle
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be8eced6-7257-4a31-a5ae-aac01139fd0d
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 80ae1dd6-4f37-4682-99fb-5950713e3a10
        userCondition: null
handle: cellQuote
hasTitleField: false
icon: quote-left
name: Zitat
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
