color: null
description: null
fieldLayouts:
  4545c033-af41-4185-9902-bc5a2d3a1727:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-17T07:37:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b84d7296-105e-4cd2-a351-d84b70fcfbfb # Article Img i18n
            handle: null
            includeInCards: false
            instructions: null
            label: Bild
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aab7cb30-7a69-4d75-8852-b683c6bcc0bf
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-06-17T11:50:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 826bddc1-fa89-4b66-b1ab-6924ab5aa9c3 # Plain Text i18n Multiline
            handle: null
            includeInCards: false
            instructions: null
            label: Bildlegende
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c030e47c-e0b7-437f-af81-73b3f83ae7a4
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-06-17T07:37:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text i18n
            handle: null
            includeInCards: false
            instructions: null
            label: Lauftext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f30374a-9c72-4d1d-8855-582e0d0139f7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 31219149-3a24-4c57-992c-cb2265cc60fc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-17T07:37:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d06e43b2-938f-4ef6-9438-70bdfaf59efa # Grid Span
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fcf1b5a-2f41-44f4-9bc7-7c36898298a9
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-06-17T07:37:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b992059d-78f2-4c88-8576-53b7f9b37a83 # Grid Start
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c184250-4f43-4b54-940e-c5a1212ef517
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-06-17T07:58:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5af8807d-9f2e-4703-a300-ba7f06531aea # Grid Span Wide
            handle: null
            includeInCards: false
            instructions: null
            label: 'Bild Grösse'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3fbda90-041e-4915-8c9b-96ecd70771d6
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-06-17T07:37:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c344dec6-0346-4e67-99e0-ec1552b8946f # Lightswitch
            handle: null
            includeInCards: false
            instructions: null
            label: 'Bild Position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5c5a6b5-4827-4471-a396-bbde5607a425
            userCondition: null
            warning: null
            width: 25
        name: Layout
        uid: 0e029fc9-5706-4fa3-b53f-2d9686a6e6f9
        userCondition: null
handle: imgTxtFloat
hasTitleField: false
icon: sheet-plastic
name: 'Bild Umfluss'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
