color: null
fieldLayouts:
  f72aed8e-11dd-49e0-ae20-bc9adbd8bc6b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-18T14:15:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f7fa055d-0e21-44e1-8772-6b44fea9a842
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-18T14:16:27+00:00'
            elementCondition: null
            fieldUid: e9282709-5d15-40a7-8b0e-f2fa08c8e74c # Coordinates
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a63b7bed-139c-4c43-a639-4a4a90dc7438
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8103a5f1-dec6-41ea-8b6c-54acf5c8d100
        userCondition: null
handle: map
hasTitleField: true
icon: map-location
name: Map
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
