color: null
description: null
fieldLayouts:
  a2bae6e5-b24f-480c-8840-77318c35fe87:
    cardThumbAlignment: end
    cardView:
      - postDate
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T10:44:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bfab3bd8-d6eb-4c0f-a8ea-461ece283cb7
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-17T09:35:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c344dec6-0346-4e67-99e0-ec1552b8946f # Lightswitch
            handle: null
            instructions: null
            label: 'Immer frei Verfügbar'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da9012aa-c2fa-4ee8-93da-e45fc5e5ac7e
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-29T07:53:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 38c1e2e9-c1e3-4c80-acfe-f190d86317fa # Plain Text i18n
            handle: null
            instructions: 'Willst du noch etwas Ballern mit dem Titel? Schrieb hier einen Catchy title (Wird nur in der Preview Card angezeigt)'
            label: 'Catchy Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fca0bd5-ade1-49b5-ae5d-fbe7f22d7304
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:10:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ccb9dece-cc63-4b57-88ad-a3010159c036
            userCondition: null
          -
            dateAdded: '2025-05-08T12:21:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 826bddc1-fa89-4b66-b1ab-6924ab5aa9c3 # Plain Text i18n Multiline
            handle: null
            instructions: null
            label: Lead
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c2a7f7d-3a80-47aa-bd26-89a7c4789197
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T10:45:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 766fa7b3-abd7-40fb-aa55-b6bda45069cd # Google Text
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 354464c7-9d21-4189-9f3a-1d1349ebce86
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:10:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3ccdefd8-e23f-41dd-95e5-7aa281a823f0
            userCondition: null
          -
            dateAdded: '2026-02-03T13:45:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8cbcac22-e63c-4df9-a8db-040cdd55daa2 # Aufmacher Bild
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e1e88be-5ef2-4ec3-a528-650a2526e112
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-19T11:13:39+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 58a37ce4-5e68-4552-af28-35bbc9e4b008
            userCondition: null
          -
            dateAdded: '2024-12-18T11:06:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 91725092-8f89-4299-a39d-14eaaeef57ae # Rubrik
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e058395e-3601-40ef-88b6-c85b0e9dcfb1
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-18T11:06:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2897cc3f-95c9-4148-80b9-fd663d11f977 # Thema
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d4dc202-9a02-4984-8cc1-3a6840b5229c
            userCondition: null
            warning: null
            width: 25
          -
            content: "# Was tun\r\n- *Aufmacherbild* Eye-Catcher zu Beginn\r\n- *Lead* Zusammenfassung und glustig macher auf den Artikel\r\n- *Google Text* wird bei den Suchresultaten angezeigt. Unglaublich wichtiger Text!!!\r\n\r\n## Foto Tool\r\n- Kein Plan, wie man Fotos fürs Web aufbereitet? Nutze [Käspus Image Resizing Tool](https://kaspar-allenbach.github.io/image-resizer/)\r\n\r\n## Texte Einfügen\r\nEs hilft, Text erst in einen [Raw Text-Editor](https://code.visualstudio.com/) einzufügen, anstatt vom Word direkt ins CMS. So wird das Word Markup automatisch gelöscht. Das CMS putzt zwar auch das Word Markup weg. Aber nicht immer.\r\n\r\n## Artikel URL\r\nDie URL wird aus dem Titel generiert. Willst du in FR eine französische URL, lösche die Zeichen im Feld `Slug` und speichere. Dann wird die URL `ASCI-Safe` neu generiert (ohne Sonderzeichen).\r\n\r\n## Catchy Title\r\nFür die Kacheln kannst du einen polemischen / lustigeren / griffigeren Titel verwenden, der dann nur auf den Kacheln dargestellt wird. Im Artikel selber kommt immer der normale titel.\r\n\r\n## Übersetzung\r\nBeim ersten Speichern eines neuen Feldes wird der Text einmalig als Referenz in die andere Sprache hinüber kopiert.\r\n\r\n## Rubrik & Thema\r\nDienen dazu, den Artikel auf den Unterseiten zu verordnen. `Lesen Sie dazu auch` wird ebenfalls aus dieser Kategorisierung automatisch generiert."
            dateAdded: '2025-04-29T06:25:34+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 02017aaf-a36b-4cac-9644-1ec620c81753
            userCondition: null
            width: 100
        name: Head
        uid: 111ec320-d642-467e-9a0a-54b565df12b6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            content: "# Was tun\r\n\r\nWürfle dir deinen Artikel aus den verschiedenen Matrix Elementen zusammen."
            dateAdded: '2025-11-19T11:13:39+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: b96dd9d7-f955-4e60-881f-0d218d5b7676
            userCondition: null
            width: 100
          -
            dateAdded: '2024-12-18T11:08:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d78e16f8-76f5-495a-a21a-bbd7cc75dc97 # ArticleBlocks
            handle: null
            instructions: null
            label: 'Artikel Blöcke'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2d32664-61c3-43b9-8325-d286c231ae69
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-08T13:10:34+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ee41adaf-27dd-4848-ae62-3ce46053b2b3
            userCondition: null
        name: Inhalt
        uid: d7eeb8cf-bc12-4c92-b8cc-3ef09c800bff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-27T12:12:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8df2a6c0-7ecc-4aef-9545-2a09ed8e8158 # SEO Articles
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e1b0956-3d57-466c-bc47-ee01df7d84d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-06T13:56:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e6243b8f-e6ab-4c5e-90a5-7f6c97b6575f # VC
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf9f4534-a990-4f46-9813-7ecab3338a51
            userCondition: null
            warning: null
            width: 100
        name: Google
        uid: 132df382-76c4-4b56-ab8f-95fb71743dd4
        userCondition: null
handle: tArticleSet
hasTitleField: true
icon: null
name: 'Article Set'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
