color: null
fieldLayouts:
  a2bae6e5-b24f-480c-8840-77318c35fe87:
    cardView:
      - postDate
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-15T10:42:47+00:00'
            elementCondition: null
            heading: 'Artikel Metadaten'
            type: craft\fieldlayoutelements\Heading
            uid: b5648445-ff66-4c03-8c5f-9fb741572f9b
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T10:44:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bfab3bd8-d6eb-4c0f-a8ea-461ece283cb7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-01T12:32:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b84d7296-105e-4cd2-a351-d84b70fcfbfb # Article Img i18n
            handle: null
            includeInCards: false
            instructions: null
            label: Aufmacherbild
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcd00616-fbe2-4880-95b3-f71b685a20f9
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-08T12:21:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 826bddc1-fa89-4b66-b1ab-6924ab5aa9c3 # Plain Text i18n Multiline
            handle: null
            includeInCards: false
            instructions: null
            label: Lead
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c2a7f7d-3a80-47aa-bd26-89a7c4789197
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-12-18T10:45:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 766fa7b3-abd7-40fb-aa55-b6bda45069cd # Google Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: 'Wird in der Google Suche dargestellt.'
            type: craft\fieldlayoutelements\CustomField
            uid: 354464c7-9d21-4189-9f3a-1d1349ebce86
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-04-23T08:10:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3ccdefd8-e23f-41dd-95e5-7aa281a823f0
            userCondition: null
          -
            dateAdded: '2024-12-18T11:06:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 91725092-8f89-4299-a39d-14eaaeef57ae # Rubrik
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e058395e-3601-40ef-88b6-c85b0e9dcfb1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-18T11:06:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2897cc3f-95c9-4148-80b9-fd663d11f977 # Thema
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d4dc202-9a02-4984-8cc1-3a6840b5229c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-15T10:42:47+00:00'
            elementCondition: null
            heading: 'Artikel Inhalt'
            type: craft\fieldlayoutelements\Heading
            uid: 2cc1b4db-84ac-41c4-9cfe-94daf1ac6420
            userCondition: null
          -
            dateAdded: '2024-12-18T11:08:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d78e16f8-76f5-495a-a21a-bbd7cc75dc97 # ArticleBlocks
            handle: null
            includeInCards: false
            instructions: null
            label: 'Artikel Blöcke'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2d32664-61c3-43b9-8325-d286c231ae69
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-08T13:10:34+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ee41adaf-27dd-4848-ae62-3ce46053b2b3
            userCondition: null
        name: Inhalt
        uid: d7eeb8cf-bc12-4c92-b8cc-3ef09c800bff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T10:52:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8615cf7b-5ca8-4def-a0f2-1370cdee3c8e # SEO Article
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d14bd53-0ba2-4789-b3c7-03556beb5ce1
            userCondition: null
            warning: null
            width: 100
        name: Google
        uid: 132df382-76c4-4b56-ab8f-95fb71743dd4
        userCondition: null
handle: tArticleSet
hasTitleField: true
icon: null
name: 'Article Set'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
