color: null
fieldLayouts:
  b1a7e021-3c5f-42e1-a2a5-39d8728567ab:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-29T07:30:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4b6337e2-afe6-4b96-a285-d544f0ff0fdc # Image Gallery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e19ae7c-cd20-4c72-974b-627c0242f9ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e5cdc8a3-8fd7-4277-b485-a3f0876e6652
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-08T13:34:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b992059d-78f2-4c88-8576-53b7f9b37a83 # Grid Start
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a33c36a-1667-4d2f-a502-f7c4cffbff7e
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-08T13:34:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d06e43b2-938f-4ef6-9438-70bdfaf59efa # Grid Span
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c9fd3ff-5d68-4f8b-917e-b749f5e40b9b
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-21T08:09:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dea6c28d-f531-465f-8aa7-a53fd66a2c6f # Vertical Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a84f0a48-ec6c-4dce-a146-fb65dab0ebf9
            userCondition: null
            warning: null
            width: 25
        name: Layout
        uid: 165cfa28-1490-4c4c-81c4-0e457b464b0c
        userCondition: null
handle: tArticleImgGallery
hasTitleField: false
icon: images
name: 'Article Image Gallery'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
