color: null
fieldLayouts:
  c1c33481-6c7d-4b77-b4f9-b5e160ddfcd2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T11:38:19+00:00'
            elementCondition: null
            heading: 'Der klassische blaue Kasten aus dem Inforaum für Zusatzinfos'
            type: craft\fieldlayoutelements\Heading
            uid: 0efc282b-8345-43f2-b1ed-9153ff62cfa4
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T11:35:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 07ae4c59-b0ad-44d8-8bfd-a1cc493e6a39
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T11:38:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text i18n
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a5e8d45-10ce-458d-b464-69f56653ca78
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 1fc15a0d-6f6a-4fc0-8e61-4c7506104737
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T07:38:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b992059d-78f2-4c88-8576-53b7f9b37a83 # Grid Start
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f1e56f5-aa14-4bfc-808d-4df081d77cf1
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-13T07:38:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d06e43b2-938f-4ef6-9438-70bdfaf59efa # Grid Span
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cfa91a8-e128-4331-a9f5-f84eb9716549
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-21T08:08:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dea6c28d-f531-465f-8aa7-a53fd66a2c6f # Vertical Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb4cd135-fa4f-4032-a4c3-1f5e2dace911
            userCondition: null
            warning: null
            width: 25
        name: Layout
        uid: 435d7c9d-1e64-4c0f-8867-202e1a3658d3
        userCondition: null
handle: tBox
hasTitleField: true
icon: cart-flatbed-boxes
name: Box
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
