color: null
fieldLayouts:
  c1c33481-6c7d-4b77-b4f9-b5e160ddfcd2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T11:38:19+00:00'
            elementCondition: null
            heading: 'Der klassische blaue Kasten aus dem Inforaum für Zusatzinfos'
            type: craft\fieldlayoutelements\Heading
            uid: 0efc282b-8345-43f2-b1ed-9153ff62cfa4
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T11:35:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 07ae4c59-b0ad-44d8-8bfd-a1cc493e6a39
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T11:38:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text i18n
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a5e8d45-10ce-458d-b464-69f56653ca78
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 1fc15a0d-6f6a-4fc0-8e61-4c7506104737
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-18T09:03:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8348b893-eaba-48e4-b4ab-15c74d5c44d0 # Typ
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66c06d27-b7de-403c-9d8f-60ce84c52266
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: 435d7c9d-1e64-4c0f-8867-202e1a3658d3
        userCondition: null
handle: tBox
hasTitleField: true
icon: cart-flatbed-boxes
name: Box
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
