color: null
fieldLayouts:
  ae37812d-9c1a-462d-aea3-f99e0053d5de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-29T09:39:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8423a2cf-6dcc-46b6-a196-16b2f63bf219 # Test, nested img
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73947028-37fa-440d-9d1b-ef7ef1869691
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d80970e-6de2-4d64-8a37-ceb08e422f59
        userCondition: null
handle: testSeparateGalleryImg
hasTitleField: false
icon: null
name: 'Test separate gallery img'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
