color: null
fieldLayouts:
  09662c87-2347-406a-9fa0-55e34d3451d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-21T06:47:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Ort
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3f76e6b3-a65a-424d-8ff2-59997ddf3f03
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-21T06:46:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fa1b164b-252f-4494-8e00-ef34899159fa # Latitude
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86127263-566f-4104-abd0-847eb16a4b8a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-21T06:46:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 004b97b7-ef5f-4e9e-a79e-0f94bebe89a8 # Longitude
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed6634d3-6fa8-4e29-8353-695684a8e427
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-21T06:47:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8caa68b5-9596-4170-82d2-20866078095e # Numer
            handle: null
            includeInCards: false
            instructions: null
            label: ZoomStufe
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0517b57-25c0-4d82-88c5-55b2646ad152
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-21T09:44:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 97b5cf10-0039-4b8a-b7ab-409f3adf851a # Plain Text
            handle: null
            includeInCards: false
            instructions: null
            label: Kartenlayer
            providesThumbs: false
            required: false
            tip: 'Layer aus der url kopieren: "ch.are.wohnungsinventar-zweitwohnungsanteil"'
            type: craft\fieldlayoutelements\CustomField
            uid: 2a7010d6-61b7-4715-a503-5a0836dfa01b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: de8accf5-1a04-48d6-b18e-0e31b1a003f0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-27T10:09:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 49c73379-624e-465f-92eb-b17550eca753 # Grid Start Wide
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4aab1d15-0b15-4d24-bec8-e28317f78b82
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-27T10:09:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5af8807d-9f2e-4703-a300-ba7f06531aea # Grid Span Wide
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3764c42-ccf5-40b4-bfac-54755d71d0da
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-21T08:10:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dea6c28d-f531-465f-8aa7-a53fd66a2c6f # Vertical Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cfd3a77-d53c-49f5-9cee-81fcabcbb80c
            userCondition: null
            warning: null
            width: 25
        name: Layout
        uid: 6e80896f-15ad-4872-b6f6-5ff3bc95e688
        userCondition: null
handle: tMap
hasTitleField: true
icon: map-location
name: Map
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
