color: null
description: null
fieldLayouts:
  3924e1cd-e4a8-4fe4-92ef-8569fc5f3213:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T09:33:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 97b5cf10-0039-4b8a-b7ab-409f3adf851a # Plain Text
            handle: null
            instructions: null
            label: Name
            required: true
            tip: 'Z.b. Hans Huber'
            type: craft\fieldlayoutelements\CustomField
            uid: 2038c0b4-d032-4c79-82f4-167d5a960968
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d4cc6a7-6165-4049-834d-ec7eae99dd50
        userCondition: null
handle: tMonolingual
hasTitleField: false
icon: person
name: 'Person Monolingual'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
