allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  63c70567-8281-4c5f-9dae-73e288e87634:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T10:26:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 826bddc1-fa89-4b66-b1ab-6924ab5aa9c3 # Plain Text i18n Multiline
            handle: null
            instructions: null
            label: Zitat
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e098318-ddaf-4aad-9071-cfc5414098be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-03T08:00:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fec3b7f5-b9a4-4f4d-8d6f-acd7061740f5 # Bildquelle
            handle: null
            instructions: null
            label: UrheberIn
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18df280a-ce33-487e-a43e-0c6469458442
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-03T08:06:34+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a2101ab1-8df4-4168-bc8c-56af5a24badb # Switch
            handle: null
            instructions: null
            label: Anführungszeichen
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8677a60e-ce78-4a3c-a1a0-6fc3f760da06
            userCondition: null
            warning: null
            width: 25
        name: Inhalt
        uid: 80ae1dd6-4f37-4682-99fb-5950713e3a10
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-03T08:00:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 49c73379-624e-465f-92eb-b17550eca753 # Grid Start Wide
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d94229de-4669-498b-a0fa-22a378cec595
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-03T08:00:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5af8807d-9f2e-4703-a300-ba7f06531aea # Grid Span Wide
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5ba0489-9693-4252-8738-6a260d27aef1
            userCondition: null
            warning: null
            width: 50
        name: Layout
        uid: 6918e779-b83a-450e-a59e-0a4cb33a17bc
        userCondition: null
    thumbFieldKey: null
handle: tQuote
hasTitleField: false
icon: quote-left
name: Quote
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
