color: null
description: null
fieldLayouts:
  0814e8a3-5733-4fa7-bb46-6db39e3f797c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-19T08:51:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9f9d456-4ae3-4b92-809a-b27d47247746 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7728de1d-f03b-4753-a60e-61ea524b8e9e
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 1b16440b-b001-44f2-a3b9-56df7bed095d
        userCondition: null
handle: tSidebarlinks
hasTitleField: false
icon: staylinked
name: SidebarLinks
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
