color: null
fieldLayouts:
  63033601-5637-49f6-8b9e-290c24c2f022:
    cardView:
      - 'layoutElement:0fd93863-06fa-4f17-a5f2-8b25a3c7d129'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T11:08:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text i18n
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fd93863-06fa-4f17-a5f2-8b25a3c7d129
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: a9620b28-6116-4747-a99a-45b96c770935
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-18T12:39:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b992059d-78f2-4c88-8576-53b7f9b37a83 # Grid Start
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac46815b-4a22-4d24-b312-de0c017d49c9
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-02-18T12:39:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d06e43b2-938f-4ef6-9438-70bdfaf59efa # Grid Span
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3da876d3-a3de-4c13-b684-af8899b3edb4
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-21T08:08:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dea6c28d-f531-465f-8aa7-a53fd66a2c6f # Vertical Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62b80aa5-ef64-499e-b103-a967ed9bcc46
            userCondition: null
            warning: null
            width: 25
        name: Layout
        uid: 3929d890-cdda-4809-b680-fb80873d635c
        userCondition: null
handle: tTxtI18n
hasTitleField: false
icon: file-lines
name: 'Text i18N'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
