color: null
fieldLayouts:
  63c70567-8281-4c5f-9dae-73e288e87634:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T10:26:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 826bddc1-fa89-4b66-b1ab-6924ab5aa9c3 # Plain Text i18n Multiline
            handle: null
            includeInCards: false
            instructions: null
            label: Zitat
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e098318-ddaf-4aad-9071-cfc5414098be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T10:26:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 97b5cf10-0039-4b8a-b7ab-409f3adf851a # Plain Text
            handle: null
            includeInCards: false
            instructions: null
            label: UrheberIn
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69647ff8-3a46-4222-9134-7d3b6fffd58e
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 80ae1dd6-4f37-4682-99fb-5950713e3a10
        userCondition: null
handle: typeQuote
hasTitleField: false
icon: quote-left
name: Quote
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
