color: null
fieldLayouts:
  5ebb01a2-ac7e-495b-bc10-8bb1b6625184:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T11:17:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fde419f4-52aa-4897-8e8d-7d10ac49031f
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-12-18T11:18:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eb32810d-6901-4788-b8bb-d4ca4124652b # H Level
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4681cdf5-dbe5-4d7e-ab94-b8d4e39db62b
            userCondition: null
            warning: null
            width: 25
        name: Inhalt
        uid: 5042406c-43fc-4495-898d-3ca36374cbdd
        userCondition: null
handle: typeSubtitle
hasTitleField: true
icon: heading
name: Subtitle
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
