allowPublicRegistration: false
deactivateByDefault: false
defaultGroup: ''
photoSubpath: null
photoVolumeUid: 288ee88d-e3ce-43e7-9cd8-371e235033c5 # Profilbild
require2fa: false
requireEmailVerification: true
validateOnPublicRegistration: false
