headingLevels:
  - 2
  - 3
  - 4
name: Article
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
  - bulletedList
  - numberedList
  - sourceEditing
  - subscript
  - superscript
  - removeFormat
