defaultPlacement: end
fieldLayouts:
  cd92531f-51f0-4ab0-85e9-9e047bd871f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T10:54:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 75b8d53e-980c-4181-9193-fb989c7305e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T09:19:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b84d7296-105e-4cd2-a351-d84b70fcfbfb # Article Img i18n
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30912ba0-5488-4b75-acaa-64d9660565ac
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-06-17T09:16:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 432db72f-cf6e-4d81-90df-eef5aeb18160 # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ca399a1-4759-424b-a697-596b228ee1f5
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-14T09:19:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text i18n
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 658dbbad-60cc-4ee1-a3f6-ea4bb6194d65
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: e72ed69c-5962-432b-b873-1a6ab58c61bb
        userCondition: null
handle: catGenre
name: Rubrik
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # Inforum FR
    hasUrls: true
    template: pages/articleByCat.twig
    uriFormat: 'genre/{slug}'
  5f286764-7e74-4475-989a-21ca80692fad: # Inforaum DE
    hasUrls: true
    template: pages/articleByCat.twig
    uriFormat: 'rubrik/{slug}'
structure:
  maxLevels: 1
  uid: 6e63c6c5-e683-4d2c-a5c5-e31e40a5eb94
