defaultPlacement: end
fieldLayouts:
  cd92531f-51f0-4ab0-85e9-9e047bd871f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T10:54:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 75b8d53e-980c-4181-9193-fb989c7305e2
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: e72ed69c-5962-432b-b873-1a6ab58c61bb
        userCondition: null
handle: catGenre
name: Rubrik
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # EspaceSuisse Publishing FR
    hasUrls: true
    template: pages/category-genre.twig
    uriFormat: 'genre/{slug}'
  5f286764-7e74-4475-989a-21ca80692fad: # EspaceSuisse Publishing DE
    hasUrls: true
    template: pages/category-genre.twig
    uriFormat: 'rubrik/{slug}'
structure:
  maxLevels: 1
  uid: 6e63c6c5-e683-4d2c-a5c5-e31e40a5eb94
