defaultPlacement: end
fieldLayouts:
  c0ce0151-0aae-4d17-9caf-abd9200a90a1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T10:53:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 027679e6-e5a3-4981-8320-2767d1c784ca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T09:19:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b84d7296-105e-4cd2-a351-d84b70fcfbfb # Article Img i18n
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eea7b5e6-eb2e-469f-a796-4f23530ba235
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-06-17T09:16:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 432db72f-cf6e-4d81-90df-eef5aeb18160 # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c116eb2-ecda-4ef4-b2f7-e20e93e641a6
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-14T09:19:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text i18n
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1f6544d-cbef-4a6e-93e9-bff1533e5fa3
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 8732783b-ab28-4e2b-9ceb-8f87d9ef6b90
        userCondition: null
handle: catSubject
name: Thema
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # Inforum
    hasUrls: true
    template: pages/articleByCat.twig
    uriFormat: 'sujet/{slug}'
  5f286764-7e74-4475-989a-21ca80692fad: # Inforaum
    hasUrls: true
    template: pages/articleByCat.twig
    uriFormat: 'thema/{slug}'
structure:
  maxLevels: 1
  uid: 7e570287-5a15-4468-b4fe-e7e1625efbde
