defaultPlacement: end
fieldLayouts:
  a14fcf5a-c5bd-4cb2-91d8-79e22e7070b5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-11T07:58:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 78a642c9-33c3-4d69-a109-13187497dd90
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bca53383-a67e-4a8c-9dc8-69f047492ef9
        userCondition: null
handle: catsource
name: catSource
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # EspaceSuisse Publishing FR
    hasUrls: true
    template: catsource/_category.twig
    uriFormat: 'catsource/{slug}'
  5f286764-7e74-4475-989a-21ca80692fad: # EspaceSuisse Publishing DE
    hasUrls: true
    template: catsource/_category.twig
    uriFormat: 'catsource/{slug}'
structure:
  maxLevels: 1
  uid: b1a469de-63b5-4b92-b663-f5033494523b
