defaultPlacement: end
fieldLayouts:
  c0ce0151-0aae-4d17-9caf-abd9200a90a1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-11T15:21:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6eb635d2-1d95-4d26-85d2-703c297243bd
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd051b0b-dbb0-4533-bb41-b1e97ca7d5c9
            userCondition: null
            warning: null
            width: 25
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T10:53:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 027679e6-e5a3-4981-8320-2767d1c784ca
            userCondition: null
            warning: 'Bei Änderung: nicht vergessen, auch den `Slug` zu ändern. `Slug` ist die `URL` der Kategorie.'
            width: 75
          -
            dateAdded: '2025-08-06T13:58:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 766fa7b3-abd7-40fb-aa55-b6bda45069cd # Google Text
            handle: null
            includeInCards: false
            instructions: 'Wird in der Google Suche angezeigt'
            label: null
            providesThumbs: false
            required: false
            tip: 'Extrem wichtiger Text: Aufgrund davon, klicken Leute in den Suchresultaten auf den Eintrag'
            type: craft\fieldlayoutelements\CustomField
            uid: 46c4c0f9-4a48-44c1-9a81-053b7cf4c485
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T09:19:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b84d7296-105e-4cd2-a351-d84b70fcfbfb # Img i18n
            handle: null
            includeInCards: false
            instructions: 'Wird z.b. auf LinkedIn als Vorschaubild angezeigt'
            label: Vorschaubild
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eea7b5e6-eb2e-469f-a796-4f23530ba235
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-06-17T09:16:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 432db72f-cf6e-4d81-90df-eef5aeb18160 # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c116eb2-ecda-4ef4-b2f7-e20e93e641a6
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-14T09:19:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09087e84-41bc-4451-91af-6be5abe8388d # Text i18n
            handle: null
            includeInCards: false
            instructions: 'Wird auf der Kategorien- Übersichtsseite dargestellt'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1f6544d-cbef-4a6e-93e9-bff1533e5fa3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-06T10:01:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c344dec6-0346-4e67-99e0-ec1552b8946f # Lightswitch
            handle: null
            includeInCards: false
            instructions: null
            label: Supertopic
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12c775f6-0dfa-4d12-98db-7afc6b4d8c65
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 8732783b-ab28-4e2b-9ceb-8f87d9ef6b90
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-06T13:58:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8df2a6c0-7ecc-4aef-9545-2a09ed8e8158 # SEO Articles
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cda29638-a9de-44ba-b35b-fd1b13fa1467
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-06T13:58:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e6243b8f-e6ab-4c5e-90a5-7f6c97b6575f # VC
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc608f80-026a-4b8f-8b3e-f31e9f693a1b
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 56af3aac-c639-434a-b9b5-45a14a7cb926
        userCondition: null
handle: catSubject
name: Thema
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # Inforum FR
    hasUrls: true
    template: pages/articleByCategory.twig
    uriFormat: 'sujet/{slug}'
  5f286764-7e74-4475-989a-21ca80692fad: # Inforaum DE
    hasUrls: true
    template: pages/articleByCategory.twig
    uriFormat: 'thema/{slug}'
structure:
  maxLevels: 1
  uid: 7e570287-5a15-4468-b4fe-e7e1625efbde
