defaultPlacement: end
fieldLayouts:
  c0ce0151-0aae-4d17-9caf-abd9200a90a1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T10:53:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 027679e6-e5a3-4981-8320-2767d1c784ca
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 8732783b-ab28-4e2b-9ceb-8f87d9ef6b90
        userCondition: null
handle: catSubject
name: Thema
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # EspaceSuisse Publishing FR
    hasUrls: true
    template: pages/category-subject.twig
    uriFormat: 'sujet/{slug}'
  5f286764-7e74-4475-989a-21ca80692fad: # EspaceSuisse Publishing DE
    hasUrls: true
    template: pages/category-subject.twig
    uriFormat: 'thema/{slug}'
structure:
  maxLevels: 1
  uid: 7e570287-5a15-4468-b4fe-e7e1625efbde
