altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4ac2d0d7-2021-4707-9d83-41dfe345e61e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T12:06:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5b190b73-04a4-4e4a-96b3-3310640fa3cf
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 4ee4e86d-9c36-4539-8f17-317360a1bbc7
        userCondition: null
fs: authorPortrait
handle: authorPortrait
name: 'Author Portrait'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: none
transformFs: ''
transformSubpath: ''
