altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a0ce3808-f12a-4f35-a8e9-687e41aee67e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T11:12:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 31299409-3c2b-499a-9053-1b108e655ad9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T11:23:27+00:00'
            elementCondition: null
            fieldUid: 97b5cf10-0039-4b8a-b7ab-409f3adf851a # Bild Quelle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5f36884-58d8-414b-a0fa-668660832f96
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 8fbc089a-23b3-4c45-a770-d16436c054c5
        userCondition: null
fs: images
handle: img
name: 'Artikel Bilder'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: ''
