altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1543690b-ffe2-4ad8-9719-82d806edeb6b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-20T10:03:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 99046a88-9a3b-4ce8-aa59-12b7ff5b4474
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b8ddae04-1612-4ffc-b020-d3600f6e4e66
        userCondition: null
fs: files
handle: vDownloads
name: Downloads
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
