altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a0ce3808-f12a-4f35-a8e9-687e41aee67e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "Bitte alles ausfüllen, so weit als möglich\r\n\r\n## Gängige Platformen:\r\n- Flickr\r\n- Unsplash\r\n- Wikimedia Commons\r\n- EspaceSuisse\r\n\r\n## Gängige Bildlizenzen:\r\n- CC BY-SA 2.0\r\n- CC BY-SA 4.0\r\n- Public Domain"
            dateAdded: '2025-03-11T08:33:10+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: ddb838f7-2890-459c-b68c-d29930868fef
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T11:12:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: 'Wird nur im Control Panel verwendet'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: 'Was sieht man auf dem Bild?'
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 31299409-3c2b-499a-9053-1b108e655ad9
            userCondition: null
            warning: 'Nicht beschreiben, wo das Bild auf der Website verwendet wird!'
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-07-22T14:00:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            instructions: 'Bild beschrieb für User mit Sehschwäche'
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 79d33ed2-79f9-4776-99f7-d7fa98a075ec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T10:55:31+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c344dec6-0346-4e67-99e0-ec1552b8946f # Lightswitch
            handle: null
            instructions: null
            label: 'Keine Bildquelle'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbdb4c38-7926-4642-873f-0ab20520c4b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T09:35:33+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\assets\AssetCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: c344dec6-0346-4e67-99e0-ec1552b8946f # Lightswitch
                  layoutElementUid: dbdb4c38-7926-4642-873f-0ab20520c4b4
                  uid: 61b4573e-a9ff-477c-9a7f-67828bcae05b
                  value: false
              elementType: craft\elements\Asset
              fieldContext: global
            elementEditCondition: null
            fieldUid: fec3b7f5-b9a4-4f4d-8d6f-acd7061740f5 # Bildquelle
            handle: null
            instructions: 'Natürliche, oder juristische Person'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bd1622b-4ce6-42e7-a383-5e90c059a56a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T12:03:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\assets\AssetCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: c344dec6-0346-4e67-99e0-ec1552b8946f # Lightswitch
                  layoutElementUid: dbdb4c38-7926-4642-873f-0ab20520c4b4
                  uid: a244c747-8087-4821-9818-f4a731c44ea6
                  value: false
              elementType: craft\elements\Asset
              fieldContext: global
            elementEditCondition: null
            fieldUid: bc09de97-2997-40ed-9f92-fb366aaaebd6 # Tag Field Provider
            handle: null
            instructions: 'Flickr, Unsplash, EspaceSuisse usw.'
            label: Platform
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0a7e850-ba44-4062-ad18-1b3a6a5a8f6e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-06-17T12:11:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\assets\AssetCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: c344dec6-0346-4e67-99e0-ec1552b8946f # Lightswitch
                  layoutElementUid: dbdb4c38-7926-4642-873f-0ab20520c4b4
                  uid: 3102cb2d-702f-4f96-bdfb-32edf7a27ad9
                  value: false
              elementType: craft\elements\Asset
              fieldContext: global
            elementEditCondition: null
            fieldUid: 02e09030-3253-478b-97e2-af4db5bdcaa1 # Image Licence
            handle: null
            instructions: 'CC BY-SA 2.0 usw.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed62dee3-a11b-4ac2-a067-071b12e1146f
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: 8fbc089a-23b3-4c45-a770-d16436c054c5
        userCondition: null
    thumbFieldKey: null
fs: images
handle: vImg
name: 'Artikel Bilder'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: ''
