altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a0ce3808-f12a-4f35-a8e9-687e41aee67e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "Bitte alles ausfüllen, so weit als möglich\r\n\r\n## Gängige Quellen:\r\n- Flickr\r\n- Unsplash\r\n- Wikimedia Commons\r\n- EspaceSuisse\r\n\r\n## Gängige Bildlizenzen:\r\n- CC BY-SA 2.0\r\n- CC BY-SA 4.0\r\n- Public Domain"
            dateAdded: '2025-03-11T08:33:10+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: ddb838f7-2890-459c-b68c-d29930868fef
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T11:12:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 31299409-3c2b-499a-9053-1b108e655ad9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T10:31:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 826bddc1-fa89-4b66-b1ab-6924ab5aa9c3 # Plain Text i18n Multiline
            handle: null
            includeInCards: false
            instructions: null
            label: 'Alt Text'
            providesThumbs: false
            required: false
            tip: 'Bild beschrieb für Leser mit Sehbehinderung.'
            type: craft\fieldlayoutelements\CustomField
            uid: 90532aec-3315-4929-89a3-182fcdc3a2a1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T11:23:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 97b5cf10-0039-4b8a-b7ab-409f3adf851a # Plain Text
            handle: null
            includeInCards: false
            instructions: null
            label: Quelle
            providesThumbs: false
            required: true
            tip: 'Alain Beuret'
            type: craft\fieldlayoutelements\CustomField
            uid: a5f36884-58d8-414b-a0fa-668660832f96
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T12:03:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bc09de97-2997-40ed-9f92-fb366aaaebd6 # Tag Field Provider
            handle: null
            includeInCards: false
            instructions: null
            label: Provider
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0a7e850-ba44-4062-ad18-1b3a6a5a8f6e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-06-17T12:11:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 02e09030-3253-478b-97e2-af4db5bdcaa1 # Image Licence
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed62dee3-a11b-4ac2-a067-071b12e1146f
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: 8fbc089a-23b3-4c45-a770-d16436c054c5
        userCondition: null
fs: images
handle: vImg
name: 'Artikel Bilder'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: ''
