altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  71e3f39a-36ac-4943-b0b6-59faa30ea72c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T13:52:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 739a3108-707a-41cd-b755-cb07543055dd
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 7266f88d-68c2-4cde-a545-32c5c0347561
        userCondition: null
fs: userPortraits
handle: vProfileImg
name: Profilbild
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: userPortraits
transformSubpath: ''
