columnSuffix: null
handle: articleImgI18n
instructions: null
name: 'Article Img i18n'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:2e1f2e2f-757e-43c1-bb5f-6f5261966f3f' # Artikel Bilder
  defaultUploadLocationSubpath: '{ craft.entries().id(object.id).site(craft.app.sites.primarySite).one().owner.slug ?? owner.slug ?? slug }'
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:2e1f2e2f-757e-43c1-bb5f-6f5261966f3f' # Artikel Bilder
  restrictedLocationSubpath: '{ craft.entries().id(object.id).site(craft.app.sites.primarySite).one().owner.slug ?? owner.slug ?? slug }'
  selectionLabel: 'Bild hinzufügen'
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: language
type: craft\fields\Assets
