columnSuffix: null
handle: fGpsSelector
instructions: 'Diese Karte dient nur der GPS Auswahl. Sie zeigt nicht den richtigen Kartenlayer oder Zoomstufe'
name: 'GPS Selector'
searchable: false
settings:
  geomanMapHeight: 500
  geomanMapLatitude: 47.99719
  geomanMapLongitude: 7.85377
  geomanMapZoom: 9
translationKeyFormat: null
translationMethod: none
type: handplant\craftgeoman\fields\Geoman
