columnSuffix: null
handle: fGridStart
instructions: null
name: 'Grid Start'
searchable: false
settings:
  defaultValue: 2
  max: 12
  min: 0
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
