columnSuffix: null
handle: fGridLeft
instructions: null
name: 'Grid Left'
searchable: false
settings:
  defaultValue: 2
  max: 12
  min: 1
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
