columnSuffix: null
handle: fGridSpanWide
instructions: null
name: 'Grid Span Wide'
searchable: false
settings:
  defaultValue: 12
  max: 12
  min: 0
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
