columnSuffix: null
handle: fGridRight
instructions: null
name: 'Grid Right'
searchable: false
settings:
  defaultValue: 10
  max: 12
  min: 1
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
