columnSuffix: null
handle: fGridWidth
instructions: null
name: 'Grid Breite'
searchable: false
settings:
  defaultValue: 10
  max: 12
  min: 1
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
