columnSuffix: null
handle: fieldCatSubject
instructions: null
name: Thema
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 3
  minRelations: 1
  selectionLabel: '+ Thema'
  showCardsInGrid: false
  showSiteMenu: false
  source: 'group:0a81db90-a5b9-4c6d-a9da-ae7489528aa3' # Thema
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
