columnSuffix: null
handle: fLinkList
instructions: null
name: 'Link List'
searchable: false
settings:
  createButtonLabel: 'Neuer Link'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - a38688d7-396c-45ae-b8b7-46b401c5e71f # Link
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
