columnSuffix: null
handle: fMxArticleBlocks
instructions: null
name: ArticleBlocks
searchable: false
settings:
  createButtonLabel: 'Artikel Element'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 5ca31310-0358-4910-9e30-5605bc0c3c17 # Subtitle
        -
          - name
          - Zwischentitel
    -
      __assoc__:
        -
          - uid
          - d4bf6dfa-d2c6-45dc-9550-68e2b143520e # Text i18N
    -
      __assoc__:
        -
          - uid
          - 2200945b-b73a-4a89-bc06-0e3927264677 # Box
    -
      __assoc__:
        -
          - uid
          - 81e82c07-b4c5-40fc-9b89-aa26efa3cae8 # Quote
        -
          - name
          - Zitat
    -
      __assoc__:
        -
          - uid
          - c0844b9c-409a-4e9f-b7a3-7511a8a6cdf1 # Image
    -
      __assoc__:
        -
          - uid
          - ba109802-9948-4c83-85bd-d61f696378a3
    -
      __assoc__:
        -
          - uid
          - f636f8a5-c9a2-4976-9ccf-f73a58c3fabf # Article Image Gallery
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
