columnSuffix: null
handle: fMxArticleBlocks
instructions: null
name: ArticleBlocks
searchable: false
settings:
  createButtonLabel: 'Artikel Element'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - d4bf6dfa-d2c6-45dc-9550-68e2b143520e # Text i18N
        -
          - name
          - Lauftext
    -
      __assoc__:
        -
          - uid
          - 5ca31310-0358-4910-9e30-5605bc0c3c17 # Subtitle
        -
          - name
          - 'Titel Abschnitt'
    -
      __assoc__:
        -
          - uid
          - 2200945b-b73a-4a89-bc06-0e3927264677 # Box
    -
      __assoc__:
        -
          - uid
          - 81e82c07-b4c5-40fc-9b89-aa26efa3cae8 # Quote
        -
          - name
          - Zitat
    -
      __assoc__:
        -
          - uid
          - c0844b9c-409a-4e9f-b7a3-7511a8a6cdf1 # Image
        -
          - name
          - Bild
    -
      __assoc__:
        -
          - uid
          - f636f8a5-c9a2-4976-9ccf-f73a58c3fabf # Article Image Gallery
        -
          - name
          - Bildergalerie
    -
      __assoc__:
        -
          - uid
          - fcc8fbb4-1672-46a2-bb5d-fbd078cf5a93
    -
      __assoc__:
        -
          - uid
          - 898d8de1-26a8-46a2-be3b-ba455a3711cc # Related Article
    -
      __assoc__:
        -
          - uid
          - bf9959dc-941c-45ef-86b1-d05efb3e1626 # Download
    -
      __assoc__:
        -
          - uid
          - 450218bb-dec8-4ecd-ac87-ba41a6674544 # Map
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
