columnSuffix: null
handle: fRichTextI18n
instructions: null
name: 'Text i18n'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: false
  headingLevels:
    - 2
    - 3
    - 4
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups: '*'
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
    - bulletedList
    - numberedList
    - sourceEditing
    - subscript
    - superscript
    - removeFormat
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
