columnSuffix: null
handle: fRichTextI18n
instructions: null
name: 'Text i18n'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 2a01649b-ab6a-4edd-a8f9-130d7d06dc53 # Article
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
