columnSuffix: null
handle: fStyling
instructions: null
name: Styling
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - A
        -
          - value
          - a
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - B
        -
          - value
          - b
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - C
        -
          - value
          - c
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
