columnSuffix: null
handle: fStyling
instructions: null
name: Styling
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'A - Standard'
        -
          - value
          - a
        -
          - icon
          - ''
        -
          - color
          - '#3e5ad3'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'B - Bisschen mehr'
        -
          - value
          - b
        -
          - icon
          - ''
        -
          - color
          - '#595959'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'C - Highlight'
        -
          - value
          - c
        -
          - icon
          - ''
        -
          - color
          - '#ff9e6c'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
