columnSuffix: null
handle: fSwisstopoLayer
instructions: '[Karten-Zusatzlayer](https://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml) `Identifier`'
name: 'Swisstopo Layer'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
