columnSuffix: null
handle: gridStartWide
instructions: null
name: 'Grid Start Wide'
searchable: false
settings:
  defaultValue: 0
  max: 12
  min: 0
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
