columnSuffix: null
handle: linkedinAuthorUrl
instructions: 'LinkedIn Profil URL des Autors'
name: 'LinkedIn Author Url'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
