columnSuffix: null
handle: mxArticleBlocks
instructions: null
name: 'Artikel Blöcke'
searchable: false
settings:
  createButtonLabel: 'Neue Textfelder'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 5ca31310-0358-4910-9e30-5605bc0c3c17 # Zwischentitel
    -
      __assoc__:
        -
          - uid
          - d4bf6dfa-d2c6-45dc-9550-68e2b143520e # Text
    -
      __assoc__:
        -
          - uid
          - c0844b9c-409a-4e9f-b7a3-7511a8a6cdf1 # Bild Monolingual
    -
      __assoc__:
        -
          - uid
          - c9a8cb19-0442-4761-af7e-5f87723586dd
    -
      __assoc__:
        -
          - uid
          - 2200945b-b73a-4a89-bc06-0e3927264677 # Kasten
    -
      __assoc__:
        -
          - uid
          - 04f7222f-7818-43e0-8dc5-5da11bcdf34f # New Chapter
    -
      __assoc__:
        -
          - uid
          - 81e82c07-b4c5-40fc-9b89-aa26efa3cae8 # Zitat
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
