columnSuffix: null
handle: mxArticleBlocks
instructions: null
name: 'Artikel Blöcke'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    - d4bf6dfa-d2c6-45dc-9550-68e2b143520e # Artikel Matrix
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
