columnSuffix: null
handle: richText
instructions: null
name: Text
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: ffa1be3d-bc59-42ca-b3ce-22e660c114d1 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
