columnSuffix: null
handle: seoArticles
instructions: null
name: 'SEO Articles'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields: ''
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoTitle
    - seoDescription
    - seoImage
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
