columnSuffix: null
handle: sticky
instructions: null
name: Sticky
searchable: false
settings:
  default: false
  offLabel: 'NO'
  onLabel: 'YES'
  showLabelsInCards: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
