columnSuffix: null
handle: textSimpleI18n
instructions: null
name: 'Text SImple i18n'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: null
  defaultTransform: null
  fullGraphqlData: true
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups: '*'
  toolbar:
    - bold
    - italic
    - '|'
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
