dateModified: 1736346886
email:
  fromEmail: kaspar.allenbach@espacesuisse.ch
  fromName: 'EspaceSuisse Publishing'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: 'Artikel Bilder'
    settings:
      path: '@assetBasePath/articleImages'
    type: craft\fs\Local
    url: '@assetBaseUrl/articleImages'
  userPortraits:
    hasUrls: true
    name: 'User Portraits'
    settings:
      path: '@assetBasePath/userPortraits'
    type: craft\fs\Local
    url: '@assetBaseUrl/userPortraits'
meta:
  __names__:
    0a81db90-a5b9-4c6d-a9da-ae7489528aa3: Thema # Thema
    2bd2e1b6-0fec-42ee-9bbb-a384eaecd9c9: Bild # Bild
    2d4ea7fb-3050-435d-806e-46986d5c58d2: 'EspaceSuisse Publishing FR' # EspaceSuisse Publishing FR
    2e063293-328e-4b38-8c35-ec4074593593: 'EspaceSuisse Publishing' # EspaceSuisse Publishing
    2e1f2e2f-757e-43c1-bb5f-6f5261966f3f: 'Artikel Bilder' # Artikel Bilder
    3bf88477-1a30-4c85-869d-a00f8943a584: 'Page Set' # Page Set
    5ca31310-0358-4910-9e30-5605bc0c3c17: Zwischentitel # Zwischentitel
    5f286764-7e74-4475-989a-21ca80692fad: 'EspaceSuisse Publishing DE' # EspaceSuisse Publishing DE
    38c1e2e9-c1e3-4c80-acfe-f190d86317fa: 'Lead Text' # Lead Text
    76bb08dd-bf89-4939-985c-3e55bff5a68d: Homepage # Homepage
    81e82c07-b4c5-40fc-9b89-aa26efa3cae8: Zitat # Zitat
    91b81ff9-4af2-440b-b42a-16821f2d0d5c: 'SEO Page' # SEO Page
    97b5cf10-0039-4b8a-b7ab-409f3adf851a: 'Bild Quelle' # Bild Quelle
    212f7ab4-64f9-4b3c-92e4-fc78442435a9: Url # Url
    288ee88d-e3ce-43e7-9cd8-371e235033c5: Profilbild # Profilbild
    766fa7b3-abd7-40fb-aa55-b6bda45069cd: 'Google Text' # Google Text
    2897cc3f-95c9-4148-80b9-fd663d11f977: Thema # Thema
    8615cf7b-5ca8-4def-a0f2-1370cdee3c8e: 'SEO Article' # SEO Article
    09087e84-41bc-4451-91af-6be5abe8388d: Text # Text
    38431ae0-6666-499d-a0a8-a2a332b0b6ce: Footnote # Footnote
    76729e35-a9d2-4cf7-aef5-11bb15688a6f: Rubrik # Rubrik
    2200945b-b73a-4a89-bc06-0e3927264677: Kasten # Kasten
    91725092-8f89-4299-a39d-14eaaeef57ae: Rubrik # Rubrik
    b572ca4f-491d-4184-8bba-ebf12597ed59: 'Zitat Quelle' # Zitat Quelle
    b885bd92-90c0-47e9-abe5-dd9464f9c0b5: Artikel # Artikel
    c0844b9c-409a-4e9f-b7a3-7511a8a6cdf1: 'Bild Monolingual' # Bild Monolingual
    d4bf6dfa-d2c6-45dc-9550-68e2b143520e: Text # Text
    d78e16f8-76f5-495a-a21a-bbd7cc75dc97: 'Artikel Blöcke' # Artikel Blöcke
    df079a13-bd61-4096-9e55-4607550dae28: Editor # Editor
    eb32810d-6901-4788-b8bb-d4ca4124652b: 'Headline Level' # Headline Level
    f98e570c-0feb-4f56-98ea-8fcd39709930: Bieldbeschrieb # Bieldbeschrieb
    fd55594d-e7ef-4114-b326-eb015c7418c9: 'Artikel Set' # Artikel Set
    ffa1be3d-bc59-42ca-b3ce-22e660c114d1: Simple # Simple
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  retour:
    edition: standard
    enabled: true
    licenseKey: VJR8JIXNP3X424S665JMYRYZ
    schemaVersion: 3.0.12
  seomatic:
    edition: standard
    enabled: true
    licenseKey: K6LZMFR5AVB04VFJEZ3O4Z9N
    schemaVersion: 3.0.12
system:
  edition: pro
  live: true
  name: 'EspaceSuisse Publishing'
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: $TZ
