dateModified: 1734511236
email:
  fromEmail: kaspar.allenbach@espacesuisse.ch
  fromName: 'EspaceSuisse Publishing'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2e063293-328e-4b38-8c35-ec4074593593: 'EspaceSuisse Publishing' # EspaceSuisse Publishing
    5f286764-7e74-4475-989a-21ca80692fad: 'EspaceSuisse Publishing' # EspaceSuisse Publishing
system:
  edition: solo
  live: true
  name: 'EspaceSuisse Publishing'
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
