dateModified: 1747821868
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:b885bd92-90c0-47e9-abe5-dd9464f9c0b5' # Artikel
      tableAttributes:
        - id
        - authors
        - 'field:91725092-8f89-4299-a39d-14eaaeef57ae' # Rubrik
        - 'field:2897cc3f-95c9-4148-80b9-fd663d11f977' # Thema
        - postDate
        - status
        - link
      type: native
    -
      heading: ''
      type: heading
    -
      key: 'section:bc7c6b58-e511-47e0-9216-7052ceafee56' # Sub Pages
      type: native
  craft\elements\User:
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - fullName
        - email
        - dateCreated
        - lastLoginDate
        - groups
      type: native
    -
      key: admins
      type: native
    -
      heading: 'Account Type'
      type: heading
    -
      key: credentialed
      type: native
    -
      key: inactive
      type: native
    -
      heading: Groups
      type: heading
    -
      key: 'group:df079a13-bd61-4096-9e55-4607550dae28' # Editor
      type: native
    -
      key: 'group:ee8b684c-14de-460c-89fd-f9fe7dd4b0cd' # EspaceSuisse
      type: native
    -
      key: 'group:1cd4c4e5-f56f-4613-9fc4-267b58ddaaee' # External Author
      type: native
email:
  fromEmail: kaspar.allenbach@espacesuisse.ch
  fromName: 'EspaceSuisse Publishing'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@assetBasePath/files'
    type: craft\fs\Local
    url: '@assetBaseUrl/files'
  images:
    hasUrls: true
    name: 'Artikel Bilder'
    settings:
      path: '@assetBasePath/articleImages'
    type: craft\fs\Local
    url: '@assetBaseUrl/articleImages'
  userPortraits:
    hasUrls: true
    name: 'User Portraits'
    settings:
      path: '@assetBasePath/userPortraits'
    type: craft\fs\Local
    url: '@assetBaseUrl/userPortraits'
meta:
  __names__:
    0a81db90-a5b9-4c6d-a9da-ae7489528aa3: Thema # Thema
    1cd4c4e5-f56f-4613-9fc4-267b58ddaaee: 'External Author' # External Author
    1f6d945b-d305-4fc1-be5f-9774e3768396: 'SEO Defaults' # SEO Defaults
    2a01649b-ab6a-4edd-a8f9-130d7d06dc53: Article # Article
    2d4ea7fb-3050-435d-806e-46986d5c58d2: 'EspaceSuisse Publishing FR' # EspaceSuisse Publishing FR
    2d392e7b-19e3-42f2-bb21-f8710194fd3f: 'Plain Text' # Plain Text
    2e063293-328e-4b38-8c35-ec4074593593: 'EspaceSuisse Publishing' # EspaceSuisse Publishing
    2e1f2e2f-757e-43c1-bb5f-6f5261966f3f: 'Artikel Bilder' # Artikel Bilder
    3bf88477-1a30-4c85-869d-a00f8943a584: 'Page Set' # Page Set
    004b97b7-ef5f-4e9e-a79e-0f94bebe89a8: Longitude # Longitude
    4b6337e2-afe6-4b96-a285-d544f0ff0fdc: 'Image Gallery' # Image Gallery
    4f2a2908-da4b-46df-b9ab-a5a6d8078286: Downloads # Downloads
    5ca31310-0358-4910-9e30-5605bc0c3c17: Subtitle # Subtitle
    5f286764-7e74-4475-989a-21ca80692fad: 'EspaceSuisse Publishing DE' # EspaceSuisse Publishing DE
    8b46b13d-a838-4abe-a6b4-e76faac177fb: File # File
    8caa68b5-9596-4170-82d2-20866078095e: Numer # Numer
    38c1e2e9-c1e3-4c80-acfe-f190d86317fa: 'Plain Text i18n' # Plain Text i18n
    76bb08dd-bf89-4939-985c-3e55bff5a68d: Homepage # Homepage
    81e82c07-b4c5-40fc-9b89-aa26efa3cae8: Quote # Quote
    91b81ff9-4af2-440b-b42a-16821f2d0d5c: 'SEO Page' # SEO Page
    97b5cf10-0039-4b8a-b7ab-409f3adf851a: 'Plain Text' # Plain Text
    288ee88d-e3ce-43e7-9cd8-371e235033c5: Profilbild # Profilbild
    766fa7b3-abd7-40fb-aa55-b6bda45069cd: 'Google Text' # Google Text
    826bddc1-fa89-4b66-b1ab-6924ab5aa9c3: 'Plain Text i18n Multiline' # Plain Text i18n Multiline
    898d8de1-26a8-46a2-be3b-ba455a3711cc: 'Related Article' # Related Article
    2897cc3f-95c9-4148-80b9-fd663d11f977: Thema # Thema
    8348b893-eaba-48e4-b4ab-15c74d5c44d0: Typ # Typ
    8615cf7b-5ca8-4def-a0f2-1370cdee3c8e: 'SEO Article' # SEO Article
    09087e84-41bc-4451-91af-6be5abe8388d: 'Text i18n' # Text i18n
    23465aca-7fa4-4dd7-bd09-9c11e7d61c9a: 'Related Entry' # Related Entry
    76729e35-a9d2-4cf7-aef5-11bb15688a6f: Rubrik # Rubrik
    450218bb-dec8-4ecd-ac87-ba41a6674544: Map # Map
    2200945b-b73a-4a89-bc06-0e3927264677: Box # Box
    9173344f-7095-45e6-a477-c0273f2b99e3: 'Plain Text I18n 2' # Plain Text I18n 2
    34360219-963c-430e-9b56-640ddc7d6eda: 'Plain Text' # Plain Text
    91725092-8f89-4299-a39d-14eaaeef57ae: Rubrik # Rubrik
    b84d7296-105e-4cd2-a351-d84b70fcfbfb: 'Article Img i18n' # Article Img i18n
    b140c349-b154-433f-9888-4b57792c9bdd: 'Alle Kategorien' # Alle Kategorien
    b572ca4f-491d-4184-8bba-ebf12597ed59: 'Plain Text Multiline' # Plain Text Multiline
    b885bd92-90c0-47e9-abe5-dd9464f9c0b5: Artikel # Artikel
    b992059d-78f2-4c88-8576-53b7f9b37a83: 'Grid Start' # Grid Start
    bc7c6b58-e511-47e0-9216-7052ceafee56: 'Sub Pages' # Sub Pages
    bf9959dc-941c-45ef-86b1-d05efb3e1626: Download # Download
    c0844b9c-409a-4e9f-b7a3-7511a8a6cdf1: Image # Image
    c344dec6-0346-4e67-99e0-ec1552b8946f: Lightswitch # Lightswitch
    d06e43b2-938f-4ef6-9438-70bdfaf59efa: 'Grid Span' # Grid Span
    d4bf6dfa-d2c6-45dc-9550-68e2b143520e: 'Text i18N' # Text i18N
    d78e16f8-76f5-495a-a21a-bbd7cc75dc97: ArticleBlocks # ArticleBlocks
    dea6c28d-f531-465f-8aa7-a53fd66a2c6f: 'Vertical Position' # Vertical Position
    df079a13-bd61-4096-9e55-4607550dae28: Editor # Editor
    eb32810d-6901-4788-b8bb-d4ca4124652b: 'H Level' # H Level
    ee8b684c-14de-460c-89fd-f9fe7dd4b0cd: EspaceSuisse # EspaceSuisse
    f636f8a5-c9a2-4976-9ccf-f73a58c3fabf: 'Article Image Gallery' # Article Image Gallery
    fa1b164b-252f-4494-8e00-ef34899159fa: Latitude # Latitude
    fcc8fbb4-1672-46a2-bb5d-fbd078cf5a93: 'Img + Txt' # Img + Txt
    fd55594d-e7ef-4114-b326-eb015c7418c9: 'Article Set' # Article Set
    ffa1be3d-bc59-42ca-b3ce-22e660c114d1: Simple # Simple
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  environment-label:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager-x:
    edition: pro
    enabled: true
    licenseKey: Q66KERQ0US0VFVKAFRDGYOPG
    schemaVersion: 4.0.0
  knock-knock:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  obfuscator:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ohdear:
    edition: standard
    enabled: true
    licenseKey: NE67WJ7K4BNECPA4BCBNHFI2
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    licenseKey: VJR8JIXNP3X424S665JMYRYZ
    schemaVersion: 3.0.12
  seomatic:
    edition: standard
    enabled: true
    licenseKey: K6LZMFR5AVB04VFJEZ3O4Z9N
    schemaVersion: 3.0.13
system:
  edition: pro
  live: true
  name: 'EspaceSuisse Publishing'
  retryDuration: null
  schemaVersion: 5.7.0.3
  timeZone: $TZ
