fieldLayouts:
  9fee3de9-d18d-4886-8bdf-5514eaf76e7f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-20T10:20:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 38c1e2e9-c1e3-4c80-acfe-f190d86317fa # Plain Text i18n
            handle: null
            includeInCards: false
            instructions: null
            label: 'Default SEO Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c97b217d-8124-49e4-823e-c701e40289ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-20T10:18:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 766fa7b3-abd7-40fb-aa55-b6bda45069cd # Google Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5de0005f-015f-4b5a-9fd1-6ebe9748f7eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-20T10:18:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b84d7296-105e-4cd2-a351-d84b70fcfbfb # Article Img i18n
            handle: null
            includeInCards: false
            instructions: null
            label: 'Default SEO Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76d0dbdb-4ee8-4687-9b77-2027f18326b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b334513c-d3ad-4ae4-ad7d-b48846b3829a
        userCondition: null
handle: seoDefaults
name: 'SEO Defaults'
sortOrder: 1
