defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d4bf6dfa-d2c6-45dc-9550-68e2b143520e # Text i18N
handle: callToAction
maxAuthors: 1
name: 'Call to Action'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # Inforum
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
  5f286764-7e74-4475-989a-21ca80692fad: # Inforaum
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
type: channel
