defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1fb49816-e800-4eb3-a679-27ea164fb72d # CTA Type
handle: callToAction
maxAuthors: 1
name: 'Call to Action'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # Inforum FR
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
  5f286764-7e74-4475-989a-21ca80692fad: # Inforaum DE
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
type: channel
