defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4e75f3d6-ff7d-43bf-8be9-7eef14e6f6eb # Homepage Set
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre Eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # Inforum FR
    enabledByDefault: true
    hasUrls: true
    template: pages/index.twig
    uriFormat: __home__
  5f286764-7e74-4475-989a-21ca80692fad: # Inforaum DE
    enabledByDefault: true
    hasUrls: true
    template: pages/index.twig
    uriFormat: __home__
type: single
