defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fbf70cb2-5720-4077-947b-c9e20c301ee6 # News Set
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # Inforum FR
    enabledByDefault: false
    hasUrls: true
    template: sections/news.twig
    uriFormat: 'actualites/{slug}'
  5f286764-7e74-4475-989a-21ca80692fad: # Inforaum DE
    enabledByDefault: false
    hasUrls: true
    template: sections/news.twig
    uriFormat: 'news/{slug}'
type: channel
