defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 04e7d3dd-0241-4ab3-83ef-72e36a2f535d # Newsletter Set Set
handle: newsletter
maxAuthors: 1
name: Newsletter
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  2d4ea7fb-3050-435d-806e-46986d5c58d2: # Inforum FR
    enabledByDefault: true
    hasUrls: true
    template: pages/newsletter.twig
    uriFormat: '{slug}'
  5f286764-7e74-4475-989a-21ca80692fad: # Inforaum DE
    enabledByDefault: true
    hasUrls: true
    template: pages/newsletter.twig
    uriFormat: '{slug}'
type: single
