name: Deploy to Green.ch Staging

on:
  push:
    branches:
      - STAGING

jobs:
  deploy:
    name: Deploy to Staging (Green.ch FTP)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout STAGING branch
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Composer dependencies (no dev)
        run: composer install --no-dev --optimize-autoloader

      - name: Prepare deploy folder
        run: |
          mkdir build

          # Copy necessary files and folders
          cp -r config build/
          cp -r templates build/
          cp -r modules build/
          cp -r plugins build/
          cp -r web build/
          cp -r vendor build/
          cp composer.json build/
          cp index.php build/ || true  # if present
          
          # Optional: Add any other needed files
          # e.g. cp robots.txt build/ or cp .htaccess build/

      - name: Deploy via FTP to Green.ch
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: build
          server-dir: ${{ secrets.PATH_STAGING }}
          exclude: |
            **/node_modules/**
            **/storage/runtime/**
            **/storage/logs/**
            **/web/assets/**
            **/web/imager/**
            **/web/cpresources/**
